theme: jekyll-theme-leap-day
title: Lab for Smart Materials and Structures (LaSMaS)
description: Research lab led by Prof. Donghyeon Ryu in the Department of Mechanical Engineering at New Mexico Tech
